server:
  port: 8282
  servlet:
    context-path: /auth-service

spring:
  application:
    name: auth-service-impl
  datasource:
    url: jdbc:postgresql://localhost:5434/auth_db
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

scheduler:
  token:
    expiration:
      delay: 10

logging:
  level:
    org:
      hibernate:
        sql: debug
    org.pharmacy.exception.handler: error
  file:
    name: logs/auth-app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

auth-service:
  shedlock:
    defaultLockAtMost: PT9S
    defaultLockAtLeast: PT3S
